permalink:    /:year/:month/:day/:title
analytics_id: UA-48997944-1
title:        Charles
description:  Personal Blog Of Wang JiZhe
url:          http://buptjz.github.com
author:       Charles
email:        buptjz@gmail.com
github:       http://github.com/BUPTJZ
keywords:     python,c,html,data mining,cloud computing
comments:     true
feed:         http://buptjz.github.com/atom.xml
ignore:       _blog, _posts/draft
markdown:     rdiscount
pygments:     true
